name: Sync metrics

on:
  issue_comment:
    types: [created, edited, deleted]
  issues:
    types: [opened, edited, deleted, labeled, unlabeled]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:       
    - uses: champnic/Porpoise@main
      env:
        GH_PAT: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
        GH_OWNER: 'champnic'
        GH_REPO: 'Porpoise'
        ADO_PAT: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
        ADO_ORG: 'microsoft'
        ADO_PROJECT: 'Edge'
