name: Sync metrics

on:
  # On issue changes and issue comments, the action will update the
  # corresponding issue.
  issue_comment:
    types: [created, edited, deleted]
  issues:
    types: [opened, edited, deleted, labeled, unlabeled]
  # But we also run once daily to update a bunch of random issues.
  # This way we can hopefully pick up issues that got new reactions
  # (reactions do not trigger issue changes).
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:       
    - uses: champnic/Porpoise@main
      env:
        GH_PAT: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
        GH_OWNER: 'champnic'
        GH_REPO: 'Porpoise'
        GH_TRACKED_LABELS: 'enhancement,tracked'
        ADO_PAT: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
        ADO_ORG: 'microsoft'
