name: test workflow

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Testing workflow
    steps:       
    - uses: champnic/Porpoise@main
      env:
        GH_PAT: '${{ secrets.GITHUB_TOKEN }}'
        GH_OWNER: 'champnic'
        GH_REPO: 'Porpoise'
        ADO_PAT: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
        ADO_ORG: 'microsoft'
        ADO_PROJECT: 'Edge'
